# Reemplaza con tus datos exactos de SonarCloud
sonar.projectKey=edgarmenor2026_laboratorio1devsecops
sonar.organization=edgarmenor2026

# Le decimos a SonarQube dónde buscar el código fuente
sonar.sources=.

# Excluimos archivos pesados o de configuración que no necesitan análisis de código
sonar.exclusions=**/*.csv, **/*.txt, Dockerfile, Jenkinsfile, **/*.md, k8s/**, .github/**

# Le indicamos el lenguaje principal
sonar.language=py
sonar.python.version=3.10