sonar.projectKey=edgarmenor2026_laboratorio1devsecops
sonar.organization=edgarmenor2026
sonar.sources=app.py,train_model.py
sonar.tests=tests
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,data/**,model/**,k8s/**,monitoring/**,.github/**
sonar.python.coverage.reportPaths=coverage.xml
