apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-app-deployment
  labels:
    app: nlp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlp-app
  template:
    metadata:
      labels:
        app: nlp-app
    spec:
      containers:
      - name: nlp-app-container
        image: us-central1-docker.pkg.dev/laboratorio1devsecops/repo-nlp/mi-app-nlp:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"