apiVersion: v1
kind: Service
metadata:
  name: nlp-app-service
spec:
  type: LoadBalancer # En un entorno local de pruebas podrías usar NodePort
  selector:
    app: nlp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Debe coincidir con el containerPort del deployment